version: '3'
services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-node
    environment:
      DB: mongodb://mongo:27017/trlogs?w=1
    depends_on:
      - mongo

  mongo:
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: trlogs
    volumes:
      - ./data/db:/data/db:rw
    ports:
      - 27017:27017
